services:
  - type: web
    name: instagram-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=1 --threads=2 --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: APIFY_TOKEN
        sync: false
