services:
  - type: web
    name: ig-scraper-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: APIFY_TOKEN
        # Set this in Render Dashboard > Environment
        sync: false